name: Cylian
main: de.rentoudu.cylian.Cylian
version: 0.3.1
author: Espher
website: http://dev.bukkit.org/server-mods/cylian/
description: >
             This lightweight minecraft server mod provides useful commands for a better minecraft experience.
commands:
  mode:
    description: Shortcut to set the game mode for the current player.
    usage: /mode [1|creative, 0|survival]
  lock:
    description: Locks a chest. You must stand directly in front of the chest. Other players will not be able to open/destory the chest until it is unlocked by it's owner (@see /unlock). Ops, can lock chests on behalf of others passing the player name as a second argument.
    usage: /lock [playerName]
  unlock:
    description: Unlocks a chest. You must stand directly in front of the chest. Ops, can unlock chests on behalf of others passing the player name as a second argument.
    usage: /unlock [playerName]
  spawn:
    description: Sets the server spawn point to players' location.
    usage: |
      /spawn set Sets the server spawn point to players' location.
      /spawn tp  Teleports the player to the spawn point location.
      /spawn display Displays the location of the current server spawn point.
  clock:
    description: Set the world time.
    aliases: t
    usage: |
      /clock [dawn|midday|dusk|midnight|number]
      /t [dawn|midday|dusk|midnight|number]
  bookmark:
    aliases: bm
    description: Bookmark system.
    usage: |
      /bookmark [add|remove] [bookmarkName] Creates or removes a bookmark based on the passed name (lower case).
      /bookmark list Lists all your previously created bookmarks.
      /bookmark [share|hide] [bookmarkName] Sets the visibility of a bookmark to public|private (@see /goto [bookmarkName] [playerName]).
  goto:
    aliases: gt
    description: Teleport yourself to a previously created bookmark. You can specify a player name as second argument to use a public bookmark.
    usage: |
      /goto [bookmarkName] This command teleports you to a previously created bookmark.
      /goto [bookmarkName] [playerName] Teleports you to a bookmark of another player, as long as the bookmark is public (@see /bookmark [share|hide]).
permissions:
  cylian.bookmark.*:
    description: Give access to all bookmark commands.
    default: true
  cylian.lock.*:
    description: Give access to all lock commands.
    default: true
  cylian.unlock.*:
    description: Give access to the unlock command.
    default: true
  cylian.goto.*:
    description: Give access to the goto command.
    default: true
  cylian.mode.*:
    description: Give access to the mode command.
    default: op
  cylian.spawn.*:
    description: Give access to the spawn command.
    default: op
  cylian.clock.*:
    description: Give access to the clock command.
    default: op
  cylian.compass.*:
    description: Give access to the compass teleport action.
    default: op